### ISSUE TITLE
Tuning missing for ZNB20

### ISSUE THREAD

**Issue by edumur** [QCoherence/python_drivers#7]
It appears that after a reset of the ZNB20, the acquisition of a trace is two times longer than necessary.
This is due to a reset of an option to 'auto' instead of 'alternative' (or the other way around).
I unfortunately don't remember the name of the option...

The problem has been fixed by manually change the parameter directly on the device.
However it will be great to have a method to tune it in remote mode.

**Comment by nicolas-experiment** [comment]
The command `SWEep:COUNt <Sweep>` defines the number of sweeps to be measured before taking the data. It only makes sense in single sweep mode (`INITiate<Ch>:CONTinuous OFF`). Maybe this does the trick.

**Comment by edumur** [comment]
After a small reading of the [manual](http://cdn.rohde-schwarz.com/pws/dl_downloads/dl_common_library/dl_manuals/gb_1/z/znb_1/ZNB_ZNBT_UserManual_en_30.pdf), I think I get the point but it turns out that now I have a new question ;) .

If I am right, what I talked in one place is ruled by the "driving mode" parameter (see page 423).
The device is by default tune to "Auto".
In this mode, it chooses the fastest sweep which is the "Alternated" mode.
To obtain the transmission in only one sweep, we have to set the driving mode to "Chopped".
This can be done with the command `[SENSe<Ch>:]COUPle <Order>` with `<Order>` is `ALL` (see page 881).

The point is now that I don't see the difference between the number of sweep parameters and the number of averaging parameter. 
To get an averaging of `N` traces shouldn't do `N` sweeps ?
If it is the case these parameters should be define by the same value, at least in the case of a simple spectroscopy.
For other mode, like two tone, I agree that things are different.

**Comment by NicoRoch** [comment]
This is solved with the new methods set_driving_mode/get_driving_mode. They allow to choose between "Auto", "Chopped" and "Alternated".
